name: test

on:
  push:
    branches: ["main", "test", "dev", "dev/*", "dev_*"]
  pull_request:
    branches: ["main", "test", "dev"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux-x86_64-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: linux-x86_64-gnu
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - build: linux-aarch64-musl
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl

          - build: linux-aarch64-gnu
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

          - build: macos-x86_64
            os: macos-latest
            target: x86_64-apple-darwin

          - build: macos-aarch64
            os: macos-latest
            target: aarch64-apple-darwin

          - build: windows-x86_64-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Tools
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy, llvm-tools

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Format with rustfmt
      run: |
        make format-check

    - name: Lint with clippy
      run: |
        make lint

    - name: Test with llvm-cov
      run: |
        make test

    - name: Build
      run: |
        make build

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        slug: AGScheduler/agscheduler-cli
        files: lcov.info
        fail_ci_if_error: true
